In [88]:
import numpy as np

In [89]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [90]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [91]:
# Get Dimension
a.ndim

1

In [92]:
# Get Shape
b.shape

(2, 3)

In [93]:
# Get Type
a.dtype

dtype('int64')

In [94]:
# Get Size
b.itemsize

8

In [95]:
# Get total size
a.nbytes

24

# Accessing/Changing specific elements, rows, columns, etc

In [96]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [97]:
# Get a specific element [r,c]
a[1,-2]

np.int64(13)

In [98]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [99]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [100]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[1, 1:-1:2]

array([ 9, 11, 13])

In [101]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


*3D example

In [102]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [103]:
# Get specific elemnt (work outside in)
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [104]:
# replace
b[:,1,:] = [[9,9],[8,8]]

## Initializing Different Types of Arrays

In [105]:
# All 0s matrix
np.zeros((2,3,3,2))

array([[[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]]])

In [106]:
# All 1s matrix
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [107]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [108]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [109]:
# or
np.full(a.shape,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [110]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.1571518 , 0.45349332],
       [0.10639163, 0.46097022],
       [0.82166517, 0.27631824],
       [0.26321527, 0.95047898]])

In [111]:
# or
np.random.random_sample(a.shape)

array([[0.41025949, 0.15531467, 0.52501105, 0.34793861, 0.56262711,
        0.64943852, 0.85517274],
       [0.74719164, 0.30615811, 0.81932104, 0.42602201, 0.25939342,
        0.9608727 , 0.36679396]])

In [112]:
# Random Integer values
np.random.randint(7)

4

In [113]:
# or
np.random.randint(8, size=(3,3))

array([[0, 1, 6],
       [4, 0, 0],
       [4, 4, 1]], dtype=int32)

In [114]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [115]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [116]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


**Be careful when copying arrays!!!**

In [117]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
print(b)


[1 2 3]
[100   2   3]


## Mathematics

In [118]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [119]:
a + 2

array([3, 4, 5, 6])

In [120]:
a - 2

array([-1,  0,  1,  2])

In [121]:
a * 2

array([2, 4, 6, 8])

In [122]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [123]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [124]:
a ** 2


array([ 1,  4,  9, 16])

In [127]:
# Take the sin
np.sin(a)
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear Algebra

In [132]:
a = np.ones((2,3))
print(a)

b = np.full((3,2), 2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [134]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

#### Statistics

In [135]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [136]:
np.min(stats)

np.int64(1)

In [137]:
np.max(stats)

np.int64(6)

In [138]:
np.max(stats, axis=1)

array([3, 6])

In [139]:
np.sum(stats, axis=0)

array([5, 7, 9])

## Reorganizing Arrays

In [141]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((8,1))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [142]:
# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [143]:
# Horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneous

#### Load Data from File

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata.astype('int32')
filedata

#### Boolean Masking and Advanced Indexing

In [ ]:
filedata[filedata > 50]

In [ ]:
## You can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

In [ ]:
np.any(filedata > 50, axis = 0)

In [ ]:
np.all(filedata > 50, axis=1)

In [ ]:
((filedata > 50) & (filedata < 100))